language: python
python:
- '3.6'
sudo: required
services:
- docker
cache: pip
env:
  global:
  - HELM_VERSION="v2.8.2"
  - DOCKER_USERNAME=captainfiaas
  - secure: "ExwVBTgGjHnuaho2epRqrbcN+6CeM1OVylQzdGpw3AVhVONpqFemypzLBxj6LaabBX7uPTU+SmqEV17dy7fhye4RwKs0w4P8tYKoJj01Cidi/voz0emhWyFiOAGiAXKoaIGYNL/g82jMfbMpFDjWT3Xbqlamh6eMM3Pk5q2LQE/LKq45zfdkISrhLEun0QModZBXEVdCLE001unuEnJPChVwmxgdn19KY9S3cIJMpYez+UQV1T+k1TRkkrfT2D3ChfAlXicO4y3H154EqdBBWZ4W1TJ8ebg8jm4RfIa0UaRljKe2q+Rx7Z0CZgdvnUxGe/NXdxErWgz5uG15dxypFdb/3Hqxtk9NkzFdTF1ZEfestIzqBAih/Ril+hS0WVYJSvLj8zC9O9dwPMeaZofJ+WM16qp1zdpJfKwRTqggNx+UC9tC/faIBwQRwKFuZVB8sA4VdHgKqKBIjgpuNEKSeLMbBg4ka+3m1Kx8nldnjskRIntm8LWZJYzlSt2brP/ilJ5pIEsSsGgRZWmG7t7MC0MTZd3inQ7dEU6lukh5sn3MzNY260GmqvgCSggdRNw/0iPtH2ACpgHhrDd1U0iNWVrJZQ/m5E8OyHCyP6n6mu58ZMr2p2bOkiOi7YGDMqTKqVK1yTyJXhgLIvngXLRaaQE/1hUpBMEy0ttwm4ljk/c=" # DOCKER_PASSWORD
install:
- pip install -e .[ci]
script:
  - tox
  - bin/docker_build
after_success:
- tox -e coverage
deploy:
  provider: script
  script: VERSION=$(python setup.py --version) TAG=$(bin/tag_release|tail -1) bash -c 'bin/docker_push && bin/publish_helm_chart'
  skip_cleanup: true
  on:
    branch: master
