name: fiaas-skipper
image:
  repository: fiaas/skipper
  tag: "latest"
  pullPolicy: Always
ingress:
  fqdn: fiaas-skipper.yourcluster.local
  enableTLS: true
  annotations: {}
  suffix: yourcluster.local
deployment:
  # include the resource requests and limits
  includeResourceUsage: true
TPR: false
CRD: true
baseurl: 'http://fiaas-release.delivery-pro.schibsted.io'
annotations: {}
rbac:
  enabled: false
statusUpdateInterval: 30
# Add a fiaas-deploy-daemon configmap to the namespace where fiaas-skipper is installed
addFiaasDeployDaemonConfigmap: false
