apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Values.name }}"
  labels:
    app: "{{ .Values.name }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
data:
  cluster_config.yaml: |-
    log-format: plain
    {{with .Values.TPR}}enable-tpr-support: {{.}}{{end}}
    {{with .Values.CRD}}enable-crd-support: {{.}}{{end}}
    {{with .Values.baseurl}}baseurl: {{.}}{{end}}
    {{with .Values.debug}}debug: true{{end}}
    {{with .Values.statusUpdateInterval}}status-update-interval: {{.}}{{end}}
    {{with not .Values.autoUpdate}}disable-autoupdate: true{{end}}
  fiaas_override.yaml: |-
{{ if .Values.fiaas_override_yaml -}}
{{ .Values.fiaas_override_yaml | indent 4 }}
{{- else -}}
{{ .Files.Get "fiaas_override.yaml" | indent 4 }}
{{- end -}}
