apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Values.name }}"
  labels:
    app: "{{ .Values.name }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
data:
  cluster_config.yaml: |-
    log-format: plain
    {{with .Values.TPR}}enable-tpr-support: {{.}}{{end}}
    {{with .Values.CRD}}enable-crd-support: {{.}}{{end}}
    {{with .Values.baseurl}}baseurl: {{.}}{{end}}
    {{with .Values.debug}}debug: true{{end}}
  fiaas_ext.yaml: |
{{ .Files.Get "fiaas_ext.yaml" | indent 4 }}
