{{- if .Values.addFiaasDeployDaemonConfigmap }}
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: fiaas-deploy-daemon
    name: fiaas-deploy-daemon
  name: fiaas-deploy-daemon
data:
  cluster_config.yaml: |-
    ingress-suffix:
    - {{ .Values.ingress.suffix }}
    {{with .Values.TPR}}enable-tpr-support: {{.}}{{end}}
    {{with .Values.CRD}}enable-crd-support: {{.}}{{end}}
{{- end}}
