apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  labels:
    app: "{{ .Values.name }}"
  name: "{{ .Values.name }}"
  annotations:
    {{- range $key, $value := .Values.ingress.annotations }}
    {{ $key }}: {{ $value }}
    {{- end }}
spec:
{{- if .Values.ingress.enableTLS }}
  tls:
  - hosts:
    - "{{ .Values.ingress.fqdn }}"
    secretName: "{{ .Values.ingress.fqdn }}"
{{- end }}
  rules:
  - host: "{{ .Values.ingress.fqdn }}"
    http:
      paths:
      - backend:
          serviceName: "{{ .Values.name }}"
          servicePort: 5000
        path: /
