apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    {{- range $key, $value := .Values.ingress.annotations }}
      {{ $key }}: {{ $value | quote }}
    {{- end }}
  labels:
    app: "{{ .Values.name }}"
  name: "{{ .Values.name }}"
spec:
{{- if .Values.ingress.enableTLS }}
  tls:
  - hosts:
    - "{{ .Values.ingress.fqdn }}"
    secretName: "{{ .Values.ingress.fqdn }}"
{{- end }}
  rules:
  - host: "{{ .Values.ingress.fqdn }}"
    http:
      paths:
      - backend:
          serviceName: "{{ .Values.name }}"
          servicePort: 5000
        path: /
