{{- if .Values.rbac.enabled }}
kind: ClusterRole
{{- if semverCompare ">=1.8" .Capabilities.KubeVersion.GitVersion }}
apiVersion: rbac.authorization.k8s.io/v1
{{- else }}
apiVersion: rbac.authorization.k8s.io/v1beta1
{{- end }}
metadata:
  name: fiaas-controller
rules:
  - apiGroups:
      - fiaas.schibsted.io
      - schibsted.io
    resources:
      - applications
      - application-statuses
      - paasbetaapplications
      - paasbetastatuses
    verbs:
      - create
      - delete
      - get
      - list
      - update
      - watch
  - apiGroups:
      - "" # "" indicates the core API group
      - apps
      - autoscaling
      - apiextensions
      - apiextensions.k8s.io
      - extensions
    resources:
      - configmaps
      - customresourcedefinitions
      - deployments
      - horizontalpodautoscalers
      - ingresses
      - pods
      - resourcequotas
      - services
      - thirdpartyresources
    verbs:
      - create
      - delete
      - get
      - list
      - update
      - watch
---
kind: ClusterRoleBinding
{{- if semverCompare ">=1.8" .Capabilities.KubeVersion.GitVersion }}
apiVersion: rbac.authorization.k8s.io/v1
{{- else }}
apiVersion: rbac.authorization.k8s.io/v1beta1
{{- end }}
metadata:
  name: fiaas-controller
subjects:
- kind: Group
  name: system:serviceaccounts
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: fiaas-controller
  apiGroup: rbac.authorization.k8s.io
{{- end }}
